# Generated by Django 4.0.4 on 2022-05-16 19:37

from django.db import migrations, models
import django.db.models.deletion
import manga.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(default='', verbose_name='Описание')),
                ('zip', models.FileField(upload_to=manga.models.manga_zip_location, verbose_name='Архив с мангой')),
                ('series', models.CharField(max_length=100, verbose_name='Серия')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('language', models.CharField(choices=[('Русский', 'Русский'), ('Английский', 'Английский'), ('Японский', 'Японский'), ('Другой', 'Другой')], max_length=100, verbose_name='Язык')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('pages', models.IntegerField(verbose_name='Кол-во страницы')),
                ('upload_date', models.DateField(auto_now_add=True, verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Манга',
                'verbose_name_plural': 'Манги',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='Имя')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('register_date', models.DateField(auto_now=True, verbose_name='Дата регистрации')),
                ('upload_amount', models.IntegerField(default=0, verbose_name='Кол-во добавленных манг')),
                ('comment_amount', models.IntegerField(default=0, verbose_name='Кол-во комментариев')),
                ('about', models.TextField(verbose_name='О себе')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='MangaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=manga.models.manga_image_location, verbose_name='Фото')),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='manga.manga', verbose_name='Манга')),
            ],
        ),
        migrations.AddField(
            model_name='manga',
            name='likes',
            field=models.ManyToManyField(blank=True, default=[0], related_name='liked_manga', to='manga.user', verbose_name='Лайки'),
        ),
        migrations.AddField(
            model_name='manga',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tagged_manga', to='manga.tag'),
        ),
        migrations.AddField(
            model_name='manga',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manga.user', verbose_name='Кто загрузил'),
        ),
    ]
