# Generated by Django 4.0.4 on 2022-05-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0005_alter_manga_pages_alter_manga_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='nsfw',
            field=models.BooleanField(default=False, verbose_name='NSFW'),
        ),
    ]
