# Generated by Django 4.0.4 on 2022-05-29 19:12

from django.db import migrations, models
import manga.models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0006_manga_nsfw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='zip',
            field=models.FileField(blank=True, upload_to=manga.models.manga_zip_location, verbose_name='Архив с мангой'),
        ),
    ]
