# Generated by Django 4.0.4 on 2022-06-02 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manga', '0007_alter_manga_zip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='Имя')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('upload_amount', models.IntegerField(default=0, verbose_name='Кол-во добавленных манг')),
                ('comment_amount', models.IntegerField(default=0, verbose_name='Кол-во комментариев')),
                ('about', models.TextField(verbose_name='О себе')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.AlterField(
            model_name='manga',
            name='likes',
            field=models.ManyToManyField(blank=True, default=[0], related_name='liked_manga', to='manga.profile', verbose_name='Лайки'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.profile', verbose_name='Кто загрузил'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
