# Generated by Django 4.0.4 on 2022-06-02 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0008_profile_alter_manga_likes_alter_manga_uploader_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
