# Generated by Django 4.0.4 on 2022-06-03 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0009_alter_profile_options_remove_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='likes',
        ),
        migrations.AlterField(
            model_name='manga',
            name='language',
            field=models.CharField(choices=[(None, 'Выберите язык'), ('Русский', 'Русский'), ('Английский', 'Английский'), ('Японский', 'Японский'), ('Другой', 'Другой')], max_length=100, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='pages',
            field=models.IntegerField(blank=True, default=0, verbose_name='Кол-во страниц'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='manga.manga', verbose_name='Лайки')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='manga.profile', verbose_name='Любимая манга')),
            ],
            options={
                'verbose_name': 'Лайк',
                'verbose_name_plural': 'Лайки',
            },
        ),
    ]
