# Generated by Django 4.0.4 on 2022-06-03 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0010_remove_manga_likes_alter_manga_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='manga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='manga.manga', verbose_name='Манга'),
        ),
        migrations.AlterField(
            model_name='like',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_manga', to='manga.profile', verbose_name='Профиль'),
        ),
    ]
