# Generated by Django 4.0.4 on 2022-06-11 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0012_remove_profile_comment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_manga', to='manga.profile', verbose_name='Кто загрузил'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фотография профиля'),
        ),
    ]
